# coding: utf-8

# flake8: noqa
"""
    Diarization documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.1.73
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from cloud_client.models.audio_dto import AudioDto
from cloud_client.models.diarization_response_dto import DiarizationResponseDto
from cloud_client.models.message_dto import MessageDto
from cloud_client.models.segment_dto import SegmentDto
from cloud_client.models.speaker_dto import SpeakerDto
from cloud_client.models.auth_response_dto import AuthResponseDto
from cloud_client.models.auth_status_dto import AuthStatusDto
from cloud_client.models.domain_dto import DomainDto
from cloud_client.models.module_names_dto import ModuleNamesDto
from cloud_client.models.auth_request_dto import AuthRequestDto
