# coding: utf-8

# flake8: noqa
"""
    Diarization documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.1.73
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from cloud_client.models.audio import Audio
from cloud_client.models.diarization_param import DiarizationParam
from cloud_client.models.diarization_response import DiarizationResponse
from cloud_client.models.diarization_result import DiarizationResult
from cloud_client.models.exception_model import ExceptionModel
from cloud_client.models.segment import Segment
from cloud_client.models.speaker import Speaker
from cloud_client.models.start_session_request import StartSessionRequest
from cloud_client.models.start_session_response import StartSessionResponse
