# coding: utf-8

"""
    Diarization documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.2.160
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from cloud_client.models.segment_dto import SegmentDto  # noqa: F401,E501


class SpeakerDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'number': 'int',
        'segments': 'list[SegmentDto]'
    }

    attribute_map = {
        'number': 'number',
        'segments': 'segments'
    }

    def __init__(self, number=None, segments=None):  # noqa: E501
        """SpeakerDto - a model defined in Swagger"""  # noqa: E501

        self._number = None
        self._segments = None
        self.discriminator = None

        if number is not None:
            self.number = number
        if segments is not None:
            self.segments = segments

    @property
    def number(self):
        """Gets the number of this SpeakerDto.  # noqa: E501


        :return: The number of this SpeakerDto.  # noqa: E501
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this SpeakerDto.


        :param number: The number of this SpeakerDto.  # noqa: E501
        :type: int
        """

        self._number = number

    @property
    def segments(self):
        """Gets the segments of this SpeakerDto.  # noqa: E501


        :return: The segments of this SpeakerDto.  # noqa: E501
        :rtype: list[SegmentDto]
        """
        return self._segments

    @segments.setter
    def segments(self, segments):
        """Sets the segments of this SpeakerDto.


        :param segments: The segments of this SpeakerDto.  # noqa: E501
        :type: list[SegmentDto]
        """

        self._segments = segments

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SpeakerDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
