# coding: utf-8

# flake8: noqa

"""
    TTS documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.1.73
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from cloud_client.api.session_api import SessionApi
from cloud_client.api.v1_api import V1Api

# import ApiClient
from cloud_client.cloud_api_client import CloudApiClient
from cloud_client.configuration import Configuration
# import models into sdk package
from cloud_client.models.close_transaction_response import CloseTransactionResponse
from cloud_client.models.credentials import Credentials
from cloud_client.models.exception_model import ExceptionModel
from cloud_client.models.session_dto import SessionDto
from cloud_client.models.start_session_request import StartSessionRequest
from cloud_client.models.status_dto import StatusDto
from cloud_client.models.synthesize_language import SynthesizeLanguage
from cloud_client.models.synthesize_request import SynthesizeRequest
from cloud_client.models.synthesize_response import SynthesizeResponse
from cloud_client.models.synthesize_sessionless_request import SynthesizeSessionlessRequest
from cloud_client.models.synthesize_text import SynthesizeText
from cloud_client.models.synthesize_voice_type import SynthesizeVoiceType
from cloud_client.models.web_socket_server_configuration import WebSocketServerConfiguration
from cloud_client.models.web_socket_synthesize_request import WebSocketSynthesizeRequest
from cloud_client.models.web_socket_text_param import WebSocketTextParam
